[package]
name = "second-task"
version = "0.1.0"
edition = "2024"

[dependencies]
hcl = { package = "hcl-rs", version = "0.19" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
